INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_T_PHOTO','PHOTO_TYPE','图片类型',0,'巡线点上传');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_T_PHOTO','PHOTO_TYPE','图片类型',1,'关键点签到');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_T_PHOTO','PHOTO_TYPE','图片类型',2,'隐患上报');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_T_PHOTO','PHOTO_TYPE','图片类型',3,'外力点上传');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_T_PHOTO','PHOTO_TYPE','图片类型',4,'外力点检查记录');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_T_PHOTO','PHOTO_TYPE','图片类型',5,'人孔检查');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_T_PHOTO','PHOTO_TYPE','图片类型',6,'隐患整治');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_T_PHOTO','PHOTO_TYPE','图片类型',7,'看护照片上传');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_MAIN_OUT_SITE','INFO_SOURCE','外力点信息来源',1,'日常巡回时现场发现');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_MAIN_OUT_SITE','INFO_SOURCE','外力点信息来源',2,'对外联系宣传时得知');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_MAIN_OUT_SITE','INFO_SOURCE','外力点信息来源',3,'施工/建设方主动告知');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_MAIN_OUT_SITE','INFO_SOURCE','外力点信息来源',4,'其他途径(电话800)');

INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_MAIN_OUT_SITE','CON_STATUS','外力点状态',1,'外力施工中');
INSERT INTO AXX_T_DICTIONARY(TABLE_NAME,TABLE_FIELD,FIELD_NAME,FIELD_NUM,NUM_EXPLAIN)VALUES('AXX_MAIN_OUT_SITE','CON_STATUS','外力点状态',2,'外力点施工结束');
commit;