
package com.linePatrol.localwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "changeCooService", targetNamespace = "http://service.changeCoordinate.webservice.com/", wsdlLocation = "http://61.160.128.47:9081/ins/services/changeCooService?wsdl")
public class ChangeCooService_Service
    extends Service
{

    private final static URL CHANGECOOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHANGECOOSERVICE_EXCEPTION;
    private final static QName CHANGECOOSERVICE_QNAME = new QName("http://service.changeCoordinate.webservice.com/", "changeCooService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://61.160.128.47:9081/ins/services/changeCooService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHANGECOOSERVICE_WSDL_LOCATION = url;
        CHANGECOOSERVICE_EXCEPTION = e;
    }

    public ChangeCooService_Service() {
        super(__getWsdlLocation(), CHANGECOOSERVICE_QNAME);
    }

    public ChangeCooService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHANGECOOSERVICE_QNAME, features);
    }

    public ChangeCooService_Service(URL wsdlLocation) {
        super(wsdlLocation, CHANGECOOSERVICE_QNAME);
    }

    public ChangeCooService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHANGECOOSERVICE_QNAME, features);
    }

    public ChangeCooService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChangeCooService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChangeCooService
     */
    @WebEndpoint(name = "ChangeCooServicePort")
    public ChangeCooService getChangeCooServicePort() {
        return super.getPort(new QName("http://service.changeCoordinate.webservice.com/", "ChangeCooServicePort"), ChangeCooService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChangeCooService
     */
    @WebEndpoint(name = "ChangeCooServicePort")
    public ChangeCooService getChangeCooServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.changeCoordinate.webservice.com/", "ChangeCooServicePort"), ChangeCooService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHANGECOOSERVICE_EXCEPTION!= null) {
            throw CHANGECOOSERVICE_EXCEPTION;
        }
        return CHANGECOOSERVICE_WSDL_LOCATION;
    }

}
