
package com.linePatrol.localwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChangeCooService", targetNamespace = "http://service.changeCoordinate.webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChangeCooService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "qryStepEquipList", targetNamespace = "http://service.changeCoordinate.webservice.com/", className = "com.webservice.changecoordinate.service.QryStepEquipList")
    @ResponseWrapper(localName = "qryStepEquipListResponse", targetNamespace = "http://service.changeCoordinate.webservice.com/", className = "com.webservice.changecoordinate.service.QryStepEquipListResponse")
    public String qryStepEquipList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "qrySiteList", targetNamespace = "http://service.changeCoordinate.webservice.com/", className = "com.webservice.changecoordinate.service.QrySiteList")
    @ResponseWrapper(localName = "qrySiteListResponse", targetNamespace = "http://service.changeCoordinate.webservice.com/", className = "com.webservice.changecoordinate.service.QrySiteListResponse")
    public String qrySiteList();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeSite", targetNamespace = "http://service.changeCoordinate.webservice.com/", className = "com.webservice.changecoordinate.service.ChangeSite")
    @ResponseWrapper(localName = "changeSiteResponse", targetNamespace = "http://service.changeCoordinate.webservice.com/", className = "com.webservice.changecoordinate.service.ChangeSiteResponse")
    public String changeSite(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeStepEquip", targetNamespace = "http://service.changeCoordinate.webservice.com/", className = "com.webservice.changecoordinate.service.ChangeStepEquip")
    @ResponseWrapper(localName = "changeStepEquipResponse", targetNamespace = "http://service.changeCoordinate.webservice.com/", className = "com.webservice.changecoordinate.service.ChangeStepEquipResponse")
    public String changeStepEquip(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
